apiVersion: apps/v1
kind: Deployment
metadata:
  name: musiclibrary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musiclibrary
  template:
    metadata:
      labels:
        app: musiclibrary
    spec:
      containers:
      - image: nemanjas23/rso-musiclibrary:0.1
        name: musiclibrary
        imagePullPolicy: "Always"
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-musiclibrary:5432/musiclibrary
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: dbuser
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: postgres
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP

